import { expect, test } from '@playwright/test'

test('creates, filters, maintains, and schedules an organization room', async ({ page }, testInfo) => {
  const suffix = Date.now().toString().slice(-6)
  const roomName = `Simulation Lab ${suffix}`
  await page.goto('/')
  await page.getByRole('button', { name: 'Rooms' }).click()
  await expect(page.getByRole('heading', { name: 'Rooms' })).toBeVisible()
  await page.getByLabel('Name').fill(roomName)
  await page.getByLabel('Capacity', { exact: true }).fill('36')
  await page.getByRole('button', { name: 'Create room' }).click()
  const room = page.locator('.room-row').filter({ hasText: roomName })
  await expect(room).toContainText('36 seats')
  await room.getByRole('button', { name: 'Maintenance' }).click()
  await expect(room).toContainText('maintenance')
  await room.getByRole('button', { name: 'Restore' }).click()
  await expect(room).toContainText('available')
  await page.getByLabel('Minimum capacity').fill('37')
  await expect(room).toHaveCount(0)
  await page.getByLabel('Minimum capacity').fill('0')

  await page.getByRole('button', { name: 'Schedule' }).click()
  await page.getByLabel('Subject / name').fill(`Clinical workshop ${suffix}`)
  await page.getByLabel('Capacity', { exact: true }).fill('20')
  await expect(page.getByLabel('Available room')).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Schedule lecture' })).toBeDisabled()
  const [availabilityResponse] = await Promise.all([
    page.waitForResponse(response => response.url().includes('/api/availability')),
    page.getByRole('button', { name: 'Search available rooms' }).click(),
  ])
  expect(availabilityResponse.status()).toBe(200)
  expect((await availabilityResponse.json()).some((available: { name: string }) => available.name === roomName)).toBe(true)
  await expect(page.getByRole('status')).toContainText('available room found')
  await page.getByLabel('Available room').selectOption({ label: `${roomName} · 36 seats` })
  await expect(page.getByRole('button', { name: 'Schedule lecture' })).toBeEnabled()
  await page.getByRole('button', { name: 'Schedule lecture' }).click()
  const reservation = page.locator('.reservation-row').filter({ hasText: `Clinical workshop ${suffix}` })
  await expect(reservation).toContainText('scheduled')
  await reservation.getByRole('button', { name: 'Reschedule' }).click()
  await page.getByLabel('Starts').fill('2026-09-01T11:00')
  await page.getByLabel('Ends').fill('2026-09-01T12:00')
  await page.getByRole('button', { name: 'Search available rooms' }).click()
  await expect(page.getByRole('status')).toContainText('available room found')
  await page.getByLabel('Available room').selectOption({ label: `${roomName} · 36 seats` })
  await page.getByRole('button', { name: 'Save new time' }).click()
  await expect(reservation).toContainText('11:00')

  await page.getByLabel('Subject / name').fill(`Conflicting workshop ${suffix}`)
  await page.getByRole('button', { name: 'Schedule lecture' }).click()
  await expect(page.getByRole('alert')).toContainText('already reserved')
  await reservation.getByRole('button', { name: 'Cancel' }).click()
  await expect(reservation).toContainText('cancelled')
  await page.screenshot({ path: testInfo.outputPath('rooms-and-schedule.png'), fullPage: true })
})
